PANDAs in Python

In [ ]:
#Importing the PANDAs library (green tick on the left of the cell means its imported successfully)
#This allows us to use the code relating to the code of pandas
import pandas as pd

In [ ]:
new_data = pd.read_csv("/content/drive/MyDrive/Think Employment Course Data/Python/pandas data class example.csv")
new_data #Add the name of the data again so we can read it, we don't need to use the print command when using the pandas library
#It will always present the first and last 5 rows

     Distance  Pulse  Maxpulse  Calories
0        60.0    110       130     409.1
1        60.0    117       145     479.0
2        60.0    103       135     340.0
3        45.0    109       175     282.4
4        45.0    117       148     406.0
..        ...    ...       ...       ...
164      60.0    105       140     290.8
165      60.0    110       145     300.0
166      60.0    115       145     310.2
167      75.0    120       150     320.4
168      75.0    125       150     330.4

[169 rows x 4 columns]

In [ ]:
new_data.head(10) #You can view the data up to the specified number of rows

   Distance  Pulse  Maxpulse  Calories
0      60.0    110       130     409.1
1      60.0    117       145     479.0
2      60.0    103       135     340.0
3      45.0    109       175     282.4
4      45.0    117       148     406.0
5      60.0    102       127     300.0
6      60.0    110       136     374.0
7      45.0    104       134     253.3
8      30.0    109       133     195.1
9      60.0     98       124     269.0

In [ ]:
new_data.tail() #This command automatically shows you the last rows instead of from the top

     Distance  Pulse  Maxpulse  Calories
164      60.0    105       140     290.8
165      60.0    110       145     300.0
166      60.0    115       145     310.2
167      75.0    120       150     320.4
168      75.0    125       150     330.4

In [ ]:
new_data.shape #This command describes how many rows by columns

(169, 4)

In [ ]:
new_data.describe() #This commmand gives us a description of the numerical statistics ONLY

#If there are any text values, it would leave them out
# Count - counts up the number of values and helps us find missing values
# Mean - give us a mean average value by adding all the values and dividing by total number of values
# Standard deviation (otherwise known as std) - measures the spread of values
# Minimum - gives us the minimum (lowest) value
# 25% - gives us the first quartile
# 50% - gives us the second quartile
# 75% - gives us the third quartile
# Max - gives us the maximum (highest) value

         Distance       Pulse    Maxpulse     Calories
count  164.000000  169.000000  169.000000   164.000000
mean    64.420732  107.461538  134.047337   375.790244
std     42.780648   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
new_data.info()

#This is a useful info command
#It is a great tool for working out the names of the columns
#It is great for working out how many null (empty) values there are
#It also shows what datatypes that are assigned to each column

#It is describing the data type in each column
#In the distance and calories columns, we can see that there are 5 missing values in each

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Distance  164 non-null    float64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 5.4 KB

In [ ]:
new_data.columns

#This lists all the column names

Index(['Distance', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')