F6 02/04/26

In [ ]:
#Import pandas
import pandas as pd

In [ ]:
#Python is Americanised, so if datasets contain pound symbols it will not install into Python
#The solution is to write the command ', encoding = "Latin1" '. This will recgonise the pound sign and the dataset can then be used.

sales_data = pd.read_csv("/content/drive/MyDrive/Think Employment Course Data/Python/Sales_Orders GSQ.csv")
sales_data

,Order ID,Order Date,Year,GDSOrder Date,Customer Name,City,State,Country,Region,Segment,Sale,Item Cost,Unit Sold,item
0,BN-2011-7407039,01/01/2011,2011,112011,Ruby Patel,Stockholm,Stockholm,SwedeN,North,Home Office,$45.00,$44.34,11,Paper
1,AZ-2011-9050313,01/03/2011,2011,132011,Summer Hayward,Southport,England,United kingdom,North,Consumer,$854.00,$853.07,26,Bookcases
2,AZ-2011-6674300,01/04/2011,2011,142011,Devin Huddleston,Valence,Auvergne-Rhône-Alpes,france,Central,Consumer,$140.00,$139.30,21,Art
3,BN-2011-2819714,01/04/2011,2011,142011,Mary Parker,Birmingham,England,United Kingdom,North,Corporate,$27.00,$26.43,22,Art
4,AZ-2011-617423,01/05/2011,2011,152011,Daniel Burke,EchirolleS,Auvergne-Rhône-Alpes,FrancE,Central,Home Office,$17.00,$16.78,1,Storage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4112,AZ-2014-8174835,12/31/2014,2014,12312014,Eloise Sykes,Bielefeld,North Rhine-Westphalia,Germany,Central,Consumer,$14.00,$13.60,11,Paper
4113,AZ-2014-766953,12/31/2014,2014,12312014,Jose Gambino,Maidenhead,England,United Kingdom,North,Corporate,$52.00,$51.14,8,Art
4114,AZ-2014-1412225,12/31/2014,2014,12312014,Leon Barnes,Worcester,England,United Kingdom,North,Consumer,$100.00,$99.47,33,Art
4115,AZ-2014-7604524,12/31/2014,2014,12312014,Rebecca Chamberlain,Hamburg,Hamburg,Germany,Central,Home Office,$136.00,$135.70,22,Supplies
4116,BN-2014-4140795,12/31/2014,2014,12312014,Daniel Hamilton,Eindhoven,North Brabant,Netherlands,Central,Home Office,$132.00,$131.52,61,Phones

In [ ]:
#How to bring up the information of a dataset
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4117 entries, 0 to 4116
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       4117 non-null   object
 1   Order Date     4117 non-null   object
 2   Year           4117 non-null   int64
 3   GDSOrder Date  4117 non-null   int64
 4   Customer Name  4117 non-null   object
 5   City           4117 non-null   object
 6   State          4117 non-null   object
 7   Country        4117 non-null   object
 8   Region         4117 non-null   object
 9   Segment        4117 non-null   object
 10  Sale           4117 non-null   object
 11  Item Cost      4117 non-null   object
 12  Unit Sold      4117 non-null   int64
 13  item           4117 non-null   object
dtypes: int64(3), object(11)
memory usage: 450.4+ KB

In [ ]:
#How to display the specific rows between a range, e.g. 60-90
sales_data.head(91).tail(5)

,Order ID,Order Date,Year,GDSOrder Date,Customer Name,City,State,Country,Region,Segment,Sale,Item Cost,Unit Sold,item
86,AZ-2011-4612792,03/12/2011,2011,3122011,Shannon Howe,Helsinki,Uusimaa,Finland,North,Consumer,$91.00,$90.63,62,Art
87,AZ-2011-7682838,03/12/2011,2011,3122011,Joseph Ford,Basel,Basel-Stadt,Switzerland,Central,Corporate,$149.00,$148.97,15,Storage
88,AZ-2011-9700826,3/14/2011,2011,3142011,Alexander Bennett,Berlin,Berlin,Germany,Central,Corporate,$112.00,$111.40,4,Art
89,AZ-2011-6222257,3/14/2011,2011,3142011,Koby Phillip,Bonn,North Rhine-Westphalia,Germany,Central,Consumer,$50.00,$49.07,6,Binders
90,AZ-2011-823697,3/14/2011,2011,3142011,Thomas McCallum,Leipzig,Saxony,Germany,Central,Consumer,$208.00,$207.29,12,Machines

In [ ]:
#How to remove a column
sales_data.drop(columns = "GDSOrder Date", inplace = True)
sales_data

,Order ID,Order Date,Year,Customer Name,City,State,Country,Region,Segment,Sale,Item Cost,Unit Sold,item
0,BN-2011-7407039,01/01/2011,2011,Ruby Patel,Stockholm,Stockholm,SwedeN,North,Home Office,$45.00,$44.34,11,Paper
1,AZ-2011-9050313,01/03/2011,2011,Summer Hayward,Southport,England,United kingdom,North,Consumer,$854.00,$853.07,26,Bookcases
2,AZ-2011-6674300,01/04/2011,2011,Devin Huddleston,Valence,Auvergne-Rhône-Alpes,france,Central,Consumer,$140.00,$139.30,21,Art
3,BN-2011-2819714,01/04/2011,2011,Mary Parker,Birmingham,England,United Kingdom,North,Corporate,$27.00,$26.43,22,Art
4,AZ-2011-617423,01/05/2011,2011,Daniel Burke,EchirolleS,Auvergne-Rhône-Alpes,FrancE,Central,Home Office,$17.00,$16.78,1,Storage
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4112,AZ-2014-8174835,12/31/2014,2014,Eloise Sykes,Bielefeld,North Rhine-Westphalia,Germany,Central,Consumer,$14.00,$13.60,11,Paper
4113,AZ-2014-766953,12/31/2014,2014,Jose Gambino,Maidenhead,England,United Kingdom,North,Corporate,$52.00,$51.14,8,Art
4114,AZ-2014-1412225,12/31/2014,2014,Leon Barnes,Worcester,England,United Kingdom,North,Consumer,$100.00,$99.47,33,Art
4115,AZ-2014-7604524,12/31/2014,2014,Rebecca Chamberlain,Hamburg,Hamburg,Germany,Central,Home Office,$136.00,$135.70,22,Supplies
4116,BN-2014-4140795,12/31/2014,2014,Daniel Hamilton,Eindhoven,North Brabant,Netherlands,Central,Home Office,$132.00,$131.52,61,Phones

How to Clean Data

In [ ]:
#How to clean data (where errors were made on purpose)
#Columns are lists, meaning it requires square brackets

sales_data["Country"].unique() #By using parentheses, we are asking python to do something that is not specified to one part of the dataset
                              #The .unique command shows unique values

array(['SwedeN', 'United kingdom', 'france', 'United Kingdom', 'FrancE',
       'France', 'FrAnce', 'ITAly', 'Austria', 'Spain', 'Germany',
       'Netherlands', 'SWEDEN', 'Denmark', 'Italy', 'Belgium', 'Norway',
       'Portugal', 'Sweden', 'Switzerland', 'Ireland', 'Finland'],
      dtype=object)

In [ ]:
#Replace the values for Sweden
sales_data["Country"] = sales_data["Country"].replace(["SwedeN","SWEDEN"], "Sweden") #The .replace command replaces values
                                                                                    #The square brackets are used to refer to a list

In [ ]:
sales_data["Country"].unique()

array(['Sweden', 'United kingdom', 'france', 'United Kingdom', 'FrancE',
       'France', 'FrAnce', 'ITAly', 'Austria', 'Spain', 'Germany',
       'Netherlands', 'Denmark', 'Italy', 'Belgium', 'Norway', 'Portugal',
       'Switzerland', 'Ireland', 'Finland'], dtype=object)

In [ ]:
#Replace the values for France

sales_data["Country"] = sales_data["Country"].replace(["FrancE","FrAnce", "france"], "France")

In [ ]:
#Replace the values for United Kingdom

sales_data["Country"] = sales_data["Country"].replace(["United kingdom"], "United Kingdom")

In [ ]:
#Replace the values for Italy

sales_data["Country"] = sales_data["Country"].replace(["ITAly"], "Italy")

In [ ]:
sales_data["Country"].unique()

array(['Sweden', 'United Kingdom', 'France', 'Italy', 'Austria', 'Spain',
       'Germany', 'Netherlands', 'Denmark', 'Belgium', 'Norway',
       'Portugal', 'Switzerland', 'Ireland', 'Finland'], dtype=object)

In [ ]:
#Check the amount of countries
num_of_countries = len(sales_data["Country"].unique()) #LEN is short for length, length is a counter
num_of_countries

15

In [ ]:
#Check the amount of cities
num_of_cities = len(sales_data["City"].unique())
num_of_cities

1005

In [ ]:
#Create a new table from the dataset we already have (in the case you want to look at a part of the dataset)

sales_data_table = sales_data[["Order Date", "Item Cost", "Unit Sold"]]
sales_data_table

      Order Date Item Cost  Unit Sold
0     01/01/2011    $44.34         11
1     01/03/2011   $853.07         26
2     01/04/2011   $139.30         21
3     01/04/2011    $26.43         22
4     01/05/2011    $16.78          1
...          ...       ...        ...
4112  12/31/2014    $13.60         11
4113  12/31/2014    $51.14          8
4114  12/31/2014    $99.47         33
4115  12/31/2014   $135.70         22
4116  12/31/2014   $131.52         61

[4117 rows x 3 columns]

In [ ]:
#Create a location table

location = sales_data[["City", "State", "Country", "Region"]]
location

            City                   State         Country   Region
0      Stockholm               Stockholm          Sweden    North
1      Southport                 England  United Kingdom    North
2        Valence    Auvergne-Rhône-Alpes          France  Central
3     Birmingham                 England  United Kingdom    North
4     EchirolleS    Auvergne-Rhône-Alpes          France  Central
...          ...                     ...             ...      ...
4112   Bielefeld  North Rhine-Westphalia         Germany  Central
4113  Maidenhead                 England  United Kingdom    North
4114   Worcester                 England  United Kingdom    North
4115     Hamburg                 Hamburg         Germany  Central
4116   Eindhoven           North Brabant     Netherlands  Central

[4117 rows x 4 columns]

In [ ]:
#Update the last row 4116

location.loc[4116] = {"City" : "Manchester" , #The .loc command locates a specific row
                       "State" : "Wigan" ,
                      "Region" : "Lancashire" ,
                      "Country" : "United Kingdom"}
location

            City                   State         Country      Region
0      Stockholm               Stockholm          Sweden       North
1      Southport                 England  United Kingdom       North
2        Valence    Auvergne-Rhône-Alpes          France     Central
3     Birmingham                 England  United Kingdom       North
4     EchirolleS    Auvergne-Rhône-Alpes          France     Central
...          ...                     ...             ...         ...
4112   Bielefeld  North Rhine-Westphalia         Germany     Central
4113  Maidenhead                 England  United Kingdom       North
4114   Worcester                 England  United Kingdom       North
4115     Hamburg                 Hamburg         Germany     Central
4116  Manchester                   Wigan  United Kingdom  Lancashire

[4117 rows x 4 columns]