F7 14/04/26

In [ ]:
import pandas as pd

In [ ]:
#Load the data
num_data = pd.read_csv("/content/drive/MyDrive/Think Employment Course Data/Python/pandas data class example.csv")
num_data

     Distance  Pulse  Maxpulse  Calories
0        60.0    110       130     409.1
1        60.0    117       145     479.0
2        60.0    103       135     340.0
3        45.0    109       175     282.4
4        45.0    117       148     406.0
..        ...    ...       ...       ...
164      60.0    105       140     290.8
165      60.0    110       145     300.0
166      60.0    115       145     310.2
167      75.0    120       150     320.4
168      75.0    125       150     330.4

[169 rows x 4 columns]

In [ ]:
#Filtering the data distances greater than 200
num_data.loc[num_data["Distance"] > 200]

     Distance  Pulse  Maxpulse  Calories
60      210.0    108       160    1376.0
69      300.0    108       143    1500.2
79      270.0    100       131    1729.0
109     210.0    137       184    1860.4

In [ ]:
#Filtering the data distances less than or equal to 100
num_data.loc[num_data["Distance"] <= 100]

     Distance  Pulse  Maxpulse  Calories
0        60.0    110       130     409.1
1        60.0    117       145     479.0
2        60.0    103       135     340.0
3        45.0    109       175     282.4
4        45.0    117       148     406.0
..        ...    ...       ...       ...
164      60.0    105       140     290.8
165      60.0    110       145     300.0
166      60.0    115       145     310.2
167      75.0    120       150     320.4
168      75.0    125       150     330.4

[148 rows x 4 columns]

In [ ]:
#Filtering the data calories more than 160
num_data.loc[num_data["Calories"] > 160]

     Distance  Pulse  Maxpulse  Calories
0        60.0    110       130     409.1
1        60.0    117       145     479.0
2        60.0    103       135     340.0
3        45.0    109       175     282.4
4        45.0    117       148     406.0
..        ...    ...       ...       ...
164      60.0    105       140     290.8
165      60.0    110       145     300.0
166      60.0    115       145     310.2
167      75.0    120       150     320.4
168      75.0    125       150     330.4

[150 rows x 4 columns]

In [ ]:
#Calculate the total distance (when you think of total, think of the sum aggregation)
total_distance = num_data ["Distance"].sum()
total_distance

np.float64(10565.0)

In [ ]:
#Calculate the minimum distance
min_distance = num_data ["Distance"].min()
min_distance

15.0

In [ ]:
#Calculate the maximum distance
max_distance = num_data ["Distance"].max()
max_distance

300.0

In [ ]:
#Calculate the mean distance (this is used to work out the missing values in a dataset)
mean_cal = num_data ["Calories"].mean()
mean_cal

np.float64(375.79024390243904)

In [ ]:
#Formatting the mean (moving the decimal places)
mean_cal = format(num_data ["Calories"].mean(), ".2f")
mean_cal

'375.79'